### ISSUE TITLE
CockroachDB

### ISSUE THREAD

**Issue by ardyhash** [ignaciofuentes/feedback#3]
Hi, Ignacio, it was a pleasure to meet you and chat. Given the marketing materials I'll take the hit of CockroachDB not being classified as a "NoSQL" database, but just wanted to share with you why I classified it as such. In the diagram below, at the lowest level, CockroachDB leverages a KV API (Key Value) to actually store the data, but uses multiple layers between that store and the client in order to present itself as SQL compatible to the clients. This way the marketing team can advertise it as an SQL database when in fact, at its core, it utilizes a NoSQL (Key Value store) backend and many layers of transformations to achieve this. Some may argue that other traditional RDBMSs also use KV Stores in the backend so I don't mind taking the hit, but thought you may be interested given that you'd read up on it recently.

https://github.com/cockroachdb/cockroach/blob/master/docs/tech-notes/sql.md

![image](https://user-images.githubusercontent.com/11933772/175560454-802e7fcb-3545-4895-ae93-53cd79c7ed7e.png)

**Comment by ignaciofuentes** [comment]
ha! that's a very valid point, Ardy! 
Thanks for that!
And absolutely I enjoyed the conversation as well.
